export const GAME_CONFIG = {
  viewport: {
    width: 480,
    height: 800,
  },
  world: {
    scrollSpeed: 220,
    maxScrollSpeed: 560,
    speedRampPerSecond: 6,
    notebookLineGap: 46,
  },
  player: {
    moveSpeed: 320,
    width: 26,
    minHeight: 40,
    maxHeight: 84,
    bottomMargin: 170,
    spriteMinDisplayHeight: 134,
    spriteMaxDisplayHeight: 190,
    tipAnchorXRatio: 187.5 / 373,
    tipAnchorYRatio: 378 / 463,
    tipOffsetX: 0,
    tipOffsetY: -8,
    trailTipSourceOffsetY: 10,
    trailPointSpacing: 6,
    trailMaxPoints: 520,
    debugTipMarker: false,
  },
  lead: {
    max: 100,
    baseDrainPerSecond: 4,
    moveDrainPerSecond: 5,
    pickupRestore: 35,
  },
  audio: {
    music: {
      key: 'gameplay-music',
      assetPath: 'assets/audio/bg-music.mp3',
      volume: 1,
      loop: true,
      basePlaybackRate: 1,
      maxPlaybackRate: 1.22,
      playbackRateRampDistanceMeters: 220,
      playbackRateSmoothingPerSecond: 6,
    },
  },
  obstacle: {
    spawnEverySeconds: 1.1,
    thickness: 14,
    minGapWidth: 120,
    maxGapWidth: 170,
    closeCallDistancePx: 16,
  },
  burn: {
    unlockAfterRows: 2,
    spawnChanceStart: 0.16,
    spawnChanceMax: 0.38,
    warningDurationMinSeconds: 0.55,
    warningDurationMaxSeconds: 0.95,
    minFootprintWidth: 44,
    maxFootprintWidth: 78,
    minFootprintHeight: 26,
    maxFootprintHeight: 48,
    minGapOverlapWidth: 18,
    maxGapOverlapWidth: 40,
    safePathPadding: 22,
    maxPlacementAttempts: 8,
  },
  celebrations: {
    linesPerMilestone: 10,
    phrases: [
      'Looking sharp!',
      'Keep scribbling!',
      "You've got this!",
      'Smooth moves!',
      'Brilliant run!',
    ],
  },
  pickups: {
    spawnEverySeconds: 2.5,
    size: 24,
    minDistanceFromObstaclePx: 18,
    spawnRetryLimit: 12,
  },
  erasers: {
    spawnEverySeconds: 3.75,
    scale: 0.56,
    minDistanceFromObstaclePx: 24,
    spawnRetryLimit: 12,
  },
  progression: {
    levelDistanceMeters: 500,
  },
  scoring: {
    pixelsPerMeter: 12,
  },
} as const;